user root wheel;
worker_processes 1;
env FF_EXTRA_EAL;
env SFC_RX_WINDOW;
master_process off;
daemon off;
fstack_conf f-stack.conf;
error_log logs/error.log info;
events {
    worker_connections 10240;
    use kqueue;
}
http {
    include mime.types;
    default_type application/octet-stream;
    access_log off;
    sendfile off;
    keepalive_timeout 65;
    keepalive_requests 100000;
    server {
        listen 80;
        server_name localhost;
        location / { root html; }
    }
}
